//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cs2Lang.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cs2Lang.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Stops cleaning up files that are not used. 的本地化字符串。
        /// </summary>
        internal static string CleanupOption {
            get {
                return ResourceManager.GetString("CleanupOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dump Error. Check files. 的本地化字符串。
        /// </summary>
        internal static string ErrorInDump {
            get {
                return ResourceManager.GetString("ErrorInDump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Files cleaned up. 的本地化字符串。
        /// </summary>
        internal static string FileCleanedUp {
            get {
                return ResourceManager.GetString("FileCleanedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Important file not found: {0} 的本地化字符串。
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Does not delete the current log file created by ModLocalizer. 的本地化字符串。
        /// </summary>
        internal static string LogOption {
            get {
                return ResourceManager.GetString("LogOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Currently in no cleanup mode. 的本地化字符串。
        /// </summary>
        internal static string NoCleanupMode {
            get {
                return ResourceManager.GetString("NoCleanupMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output:  的本地化字符串。
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tmod file 的本地化字符串。
        /// </summary>
        internal static string PathArgument {
            get {
                return ResourceManager.GetString("PathArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Syntax: tmod_path mod_namespace(without whitespace) 的本地化字符串。
        /// </summary>
        internal static string PathArgumentDetail {
            get {
                return ResourceManager.GetString("PathArgumentDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Killed process... Error reported. 的本地化字符串。
        /// </summary>
        internal static string ProcessKilled {
            get {
                return ResourceManager.GetString("ProcessKilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///Details
        ///-----------------------------
        ///Main core of this program is Mod.Localizer v0.2. Make sure this folder is here with the program.
        ///This program is a package for ModLocalizer which transfers .json files to .lang files. 的本地化字符串。
        /// </summary>
        internal static string ProgramDetail {
            get {
                return ResourceManager.GetString("ProgramDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cs2Lang  Version {0} 的本地化字符串。
        /// </summary>
        internal static string ProgramInfo {
            get {
                return ResourceManager.GetString("ProgramInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replaces with the words and sentences in the specified file in the .lang file. 的本地化字符串。
        /// </summary>
        internal static string ReplaceOption {
            get {
                return ResourceManager.GetString("ReplaceOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specify TML file path and mod&apos;s namespace name.
        ///Format: .\Cs2Lang.exe mod_path mod_namespace_name 的本地化字符串。
        /// </summary>
        internal static string SpecificPath {
            get {
                return ResourceManager.GetString("SpecificPath", resourceCulture);
            }
        }
    }
}
